name: svelte_web_examples
description: Svelte WEB examples.
version: 1.0.0-dev.1
repository: https://github.com/ykmnkmi/svelte.dart
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1
  svelte_web_runtime: 1.0.0-dev.1

dev_dependencies:
  build_runner: ^2.4.5
  build_web_compilers: ^4.0.3
  lints: ^2.1.0
