name: expression
description: Parser and utilities for Dart expressions.
version: 1.0.0-dev.7

environment:
  sdk: '>=2.13.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0
  lints: ^1.0.0
  stack_trace: ^1.10.0
