name: expression
description: Parser and utilities for Dart expressions.
version: 1.0.0+8

environment:
  sdk: '>=2.14.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.0
  build_web_compilers: ^3.2.0
  lints: ^1.0.0
  stack_trace: ^1.10.0
