
include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - example/**
  language:
    strict-inference: true
    strict-raw-types: true
  strong-mode:
    implicit-dynamic: false
    implicit-casts: false

linter:
  rules:
    avoid_print: true