include: package:lints/recommended.yaml

analyzer:
  exclude:
    - build/*
  language:
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    avoid_print: true
    implementation_imports: false
    library_prefixes: false