global_options:
  build_web_compilers|entrypoint:
    options:
      # compiler: dart2js
      dart2js_args:
        # - --verbose
        # - --disable-inlining
        # - --no-source-maps

        - --minify
        - --lax-runtime-type-to-string
        # - --omit-late-names
        - --omit-implicit-checks
        - --trust-primitives
        # - --omit-as-casts
        # - --server-mode

        # - --csp

targets:
  $default:
    builders:
      build_web_compilers:entrypoint:
        generate_for:
          - web/**.dart
