builders:
  svelte:
    import: "package:svelte/builders.dart"
    builder_factories:
      - svelteBuilder
    auto_apply: dependents
    build_to: cache
    build_extensions:
      ".svelte":
        - ".svelte.dart"

targets:
  $default:
    builders:
      build_web_compilers:entrypoint:
        generate_for:
          - lib/runtime.dart
          - lib/runtime/**.dart
          - lib/svelte.dart
          - web/**.dart
        options:
          native_null_assertions: false
          dart2js_args:
            # - -O0
            # - --disable-inlining
            # - --disable-type-inference
            # - --disable-rti-optimizations

            # - -O1

            # - -O2
            - --minify
            - --lax-runtime-type-to-string
            # - --omit-late-names

            # - -O3
            - --omit-implicit-checks

            # - -O4
            - --trust-primitives

            # - --csp
            # - --enable-asserts
            # - --no-source-maps
            # - --omit-as-casts
            # - --server-mode
            # - --verbose

      svelte:svelte:
        enabled: false
