global_options:
  build_web_compilers|entrypoint:
    options:
      native_null_assertions: false
      dart2js_args:
        # - -O0
        # - --verbose
        # - --disable-inlining
        # - --no-source-maps

        # - -O1

        # - -O2
        # - --minify
        - --lax-runtime-type-to-string
        - --omit-late-names

        # - -O3
        - --omit-implicit-checks

        # - -O4
        - --trust-primitives

        # - --omit-as-casts
        # - --enable-asserts
        # - --server-mode
        # - --csp

targets:
  $default:
    builders:
      build_web_compilers:entrypoint:
        generate_for:
          - web/**.dart
