part of angular_ast.src.token.tokens;

enum SimpleTokenType {
  atSign,
  bang,
  backSlash,
  closeBanana,
  closeBrace,
  closeBracket,
  closeParen,
  closeTagStart,
  commentBegin,
  commentEnd,
  dash,
  doubleQuote,
  openTagStart,
  tagEnd,
  equalSign,
  eof,
  forwardSlash,
  hash,
  identifier,
  mustacheBegin,
  mustacheEnd,
  openBanana,
  openBrace,
  openBracket,
  openParen,
  period,
  percent,
  singleQuote,
  star,
  text,
  unexpectedChar,
  voidCloseTag,
  whitespace,
}

enum TokenType {
  annotationPrefix,
  bananaPrefix,
  bananaSuffix,
  bindPrefix, // Not used in NgScanner.
  beforeElementDecorator,
  beforeElementDecoratorValue,
  closeElementEnd,
  closeElementStart,
  commentEnd,
  commentStart,
  commentValue,
  doubleQuote,
  elementDecorator,
  elementDecoratorValue,
  elementIdentifier,
  eventPrefix,
  eventSuffix,
  interpolationEnd,
  interpolationStart,
  interpolationValue,
  letPrefix,
  openElementEnd,
  openElementEndVoid,
  openElementStart,
  onPrefix, // Not used in NgScanner.
  propertyPrefix,
  propertySuffix,
  referencePrefix,
  singleQuote,
  templatePrefix,
  text,
  whitespace,
}
