name: svelte_runtime
description: SvelteDart Runtime.
version: 1.0.0-dev.4
repository: https://github.com/ykmnkmi/svelte.dart

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  js: ^0.6.7
  meta: ^1.11.0

dev_dependencies:
  lints: ^3.0.0
  stack_trace: ^1.11.1
  test: ^1.24.9
