name: svelte_runtime
description: SvelteDart Runtime.
version: 1.0.0-dev.6
repository: https://github.com/ykmnkmi/svelte.dart

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  meta: ^1.14.0
  web: ^0.5.1

dev_dependencies:
  lints: ^3.0.0
  stack_trace: ^1.11.1
  test: ^1.25.4
