name: svelte_runtime
description: SvelteDart Runtime.
version: 1.0.0-dev.13
repository: https://github.com/ykmnkmi/svelte.dart

resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  meta: ^1.17.0
  web: ^1.1.1

dev_dependencies:
  lints: ^6.0.0
  stack_trace: ^1.12.1
  test: ^1.26.2
