name: svelte_component
description: SvelteDart component base.
version: 1.0.0-dev.0
repository: https://github.com/ykmnkmi/svelte.dart
publish_to: none

resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  meta: ^1.16.0
  svelte_runtime: ^1.0.0-dev.7
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.14
  build_web_compilers: ^4.1.0
  lints: ^5.1.0
