name: angular_ast
repository: https://github.com/angulardart/angular
description: Parser and utilities for AngularDart templates
version: 2.0.2+5

environment:
  sdk: '>=2.15.0-0 <3.0.0'

dependencies:
  analyzer: ^2.6.0
  charcode: ^1.3.1
  collection: ^1.15.0
  meta: ^1.7.0
  source_span: ^1.8.1
  string_scanner: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.4
  lints: ^1.0.1
  path: ^1.8.0
  test: ^1.18.2
