name: svelte_web_runtime
description: SvelteDart WEB runtime library.
version: 1.0.0-dev.0
repository: https://github.com/ykmnkmi/svelte.dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1

dev_dependencies:
  lints: ^2.1.0
  stack_trace: ^1.11.0
  test: ^1.24.3
