name: svelte_ast
description: AST, Parser and utilities for SvelteDart templates.
version: 1.0.0-dev.19
repository: https://github.com/ykmnkmi/svelte.dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ">=5.13.0 <5.14.0"
  csslib: ^1.0.0
  meta: ^1.9.1
  source_span: ^1.10.0

dev_dependencies:
  collection: ^1.17.2
  lints: ^2.1.0
  stack_trace: ^1.11.0
  test: ^1.24.3
