targets:
  $default:
    builders:
      build_web_compilers:entrypoint:
        generate_for:
          - web/main.dart
        options:
          native_null_assertions: false
        dev_options:
          compilers:
            dartdevc:
        release_options:
          compilers:
            dart2js:
              args:
                # - -O0
                # - --disable-inlining
                # - --disable-type-inference
                # - --disable-rti-optimizations

                # - -O1

                # - -O2
                # - --minify
                # - --lax-runtime-type-to-string
                # - --omit-late-names

                # - -O3
                # - --no-native-null-assertions
                # - --omit-implicit-checks

                - -O4
                # - --trust-primitives

                # - --csp
                # - --enable-asserts
                - --no-minify
                # - --no-source-maps
                # - --omit-as-casts
                # - --verbose
            dart2wasm:
              args:
                # - -O0
                - --no-minify

                # - -O1
                # - --inlining

                # - -O2
                # - --minify

                # - -O3
                # - --omit-implicit-checks

                - -O4
                # - --omit-bounds-checks

                # - --no-strip-wasm
                # - --enable-asserts
                # - --no-source-maps
                # - --verbose
