targets:
  $default:
    builders:
      build_web_compilers:entrypoint:
        generate_for:
          - web/*.dart
        options:
          native_null_assertions: false
          dart2js_args:
            # - -O0
            # - --disable-inlining
            # - --disable-type-inference
            # - --disable-rti-optimizations

            # - -O1

            # - -O2
            # - --minify
            # - --lax-runtime-type-to-string
            # - --omit-late-names

            # - -O3
            # - --no-native-null-assertions
            # - --omit-implicit-checks

            - -O4
            # - --trust-primitives

            # - --csp
            # - --enable-asserts
            - --no-minify
            # - --no-source-maps
            # - --omit-as-casts
            # - --verbose
