name: svelte_js
description: An absolute bare-bones web app.
version: 1.0.0-dev.0
publish_to: none

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  js: ^0.6.7
  meta: ^1.11.0

dev_dependencies:
  build_runner: ^2.4.7
  build_web_compilers: ^4.0.8
  lints: ^3.0.0
