name: svelte_js
description: An absolute bare-bones web app.
version: 1.0.0-dev.10
publish_to: none

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  meta: ^1.12.0
  web: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^3.0.0
