name: jsx
description: JSX like DartX components.
version: 1.0.0-dev.2
homepage: https://piko.ykmnkmi.dev

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  piko: ^1.0.0-dev
  meta: ^1.5.0

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0
  frontend_server_client: ^2.0.0
  lints: ^1.0.0
  path: ^1.8.0
  stack_trace: ^1.10.0
  stream_transform: ^2.0.0

dependency_overrides:
  piko:
    path: ../..
  