name: svelte_compiler
description: SvelteDart compiler library.
version: 1.0.0-6.dev
repository: https://github.com/ykmnkmi/svelte.dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  _fe_analyzer_shared: any
  analyzer: ">=6.0.0 <6.3.0"
  csslib: ^1.0.0
  meta: ^1.10.0
  source_span: ^1.10.0
  svelte_ast: 1.0.0-9.beta

dev_dependencies:
  lints: ^2.1.0
  stack_trace: ^1.11.1
