name: svelte_compiler
description: SvelteDart compiler library.
version: 1.0.0-dev.0
repository: https://github.com/ykmnkmi/svelte.dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1
  svelte_ast: 1.0.0-beta.2

dev_dependencies:
  lints: ^2.1.1
