include: package:lints/recommended.yaml

analyzer:
  exclude:
    - build/*
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    avoid_print: true
    library_prefixes: false
