builders:
  svelte_builder:
    import: package:svelte_builder/svelte_builder.dart
    builder_factories:
      - svelteBuilder
    auto_apply: dependents
    build_to: source
    build_extensions:
      .svelte:
        - .svelte.html
        - .svelte.instance.dart
        - .svelte.module.dart
        - .svelte.dart
